version: '3'
services:
  product-service:
    build: ./product-service
    environment:
      - "DATABASE_NAME=producto"
      - CONFIG_HOST=config-service
      - EUREKA_HOST=eureka-service
      - WAIT_HOSTS=eureka-service:8761
    networks:
      - local
  producto:
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"

    networks:
      - local
    volumes:
      - ./db:/var/lib/db/producto
      - ./product-service/sql/product.sql:/docker-entrypoint-initdb.d/init.sql

    expose:
      - 5432


  config-service:
    build: ./config-service
    networks:
      - local
    expose:
      - 8086
  eureka-service:
    build: ./eureka-service
    environment:
      - CONFIG_HOST=config-service
      - WAIT_HOSTS=config-service:8086
    networks:
      - local
    expose:
      - 8761
networks:
  local: