version: '3'
services:
  product-service:
    build: ./product-service
    environment:
      - "DATABASE_NAME=producto"
  producto:
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"

    volumes:
      - ./db:/var/lib/db/producto
      - ./product-service/sql/product.sql:/docker-entrypoint-initdb.d/init.sql

    expose:
      - 5432

  gateway-service:
    build: ./gateway-service

  config-service:
    build: ./config-service

  eureka-service:
    build: ./eureka-service
