version: '3'
services:
  product-service:
    build: ./product-service
    ports:
      - "8081:8080"
    environment:
      - WAIT_HOSTS=eureka-service:8761
      - CONFIG_HOST=config-service
      - EUREKA_HOST=eureka-service
    depends_on:
      - eureka-service
    links:
      - eureka-service

  config-service:
    build: ./config-service
    ports:
      - "8086:8086"
    expose:
      - 8086

  eureka-service:
    build: ./eureka-service
    environment:
      - CONFIG_HOST=config-service
      - WAIT_HOSTS=config-service:8086
    ports:
      - "8761:8761"
    links:
      - config-service
    expose:
      - 8761
