server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/authdb
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect    
    hibernate:
      generate-ddl: true
      ddl-auto: create
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: http://${EUREKA_HOST:localhost}:8761/eureka}
  instance: 
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
