server:
  port: 8081

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      filter:
        circuit-breaker:
          enabled: true
        redirect-to:
          enabled: true
      httpclient:
        connect-timeout: 90000
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:4200"
              allowedHeaders: "*"
              allowedMethods:
              - GET
              - POST
              - DELETE
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/review/**
