server:
  port: 8080

spring:
  sql.init.mode: always
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform.database-platform: org.hibernate.dialect.H2Dialect


eureka:
  client:
    service-url:
      default-zone: http://{EUREKA_HOST:localhost}:8761/eureka/
