server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/productdb
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance: 
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
