server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/reviewdb
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect    
    hibernate:
      generate-ddl: true
      ddl-auto: create

eureka:
  instance: 
    instance-id: ${spring.application.name}:${spring.application.instance_id:8085}
  client:    
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
