server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: tfg
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: http://localhost:8761/eureka
    instance: 
      hostname: localhost