version: '3'
services:
  product-service:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "DATABASE_NAME=producto"
  producto:
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=root"

    volumes:
      - ./db:/var/lib/db/producto
      - ./sql/product.sql::/docker-entrypoint-initdb.d/init.sql"

    expose:
      - 5432

