server:
  port: 8086

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DavidGL99/tfg-services
          searchPaths: config-data
          default-label: master

